/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Recieve.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Recieve.pb-c.h"
void   device_to_host__frame__init
                     (DeviceToHost__Frame         *message)
{
  static const DeviceToHost__Frame init_value = DEVICE_TO_HOST__FRAME__INIT;
  *message = init_value;
}
size_t device_to_host__frame__get_packed_size
                     (const DeviceToHost__Frame *message)
{
  assert(message->base.descriptor == &device_to_host__frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_to_host__frame__pack
                     (const DeviceToHost__Frame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_to_host__frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_to_host__frame__pack_to_buffer
                     (const DeviceToHost__Frame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_to_host__frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceToHost__Frame *
       device_to_host__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceToHost__Frame *)
     protobuf_c_message_unpack (&device_to_host__frame__descriptor,
                                allocator, len, data);
}
void   device_to_host__frame__free_unpacked
                     (DeviceToHost__Frame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_to_host__frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor device_to_host__frame__field_descriptors[14] =
{
  {
    "Current_Pitch_",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, current_pitch_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Current_Yaw_",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, current_yaw_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Current_Roll_",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, current_roll_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Current_Color_",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, current_color_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Bullet_Speed_",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, bullet_speed_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mode_",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, mode_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Enemies_Blood_0",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, enemies_blood_0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Enemies_Blood_1",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, enemies_blood_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Enemies_Blood_2",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, enemies_blood_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Enemies_Blood_3",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, enemies_blood_3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Enemies_Blood_4",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, enemies_blood_4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Enemies_Blood_5",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, enemies_blood_5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Enemies_outpost",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, enemies_outpost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "IfAttackEngineer",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceToHost__Frame, ifattackengineer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_to_host__frame__field_indices_by_name[] = {
  4,   /* field[4] = Bullet_Speed_ */
  3,   /* field[3] = Current_Color_ */
  0,   /* field[0] = Current_Pitch_ */
  2,   /* field[2] = Current_Roll_ */
  1,   /* field[1] = Current_Yaw_ */
  6,   /* field[6] = Enemies_Blood_0 */
  7,   /* field[7] = Enemies_Blood_1 */
  8,   /* field[8] = Enemies_Blood_2 */
  9,   /* field[9] = Enemies_Blood_3 */
  10,   /* field[10] = Enemies_Blood_4 */
  11,   /* field[11] = Enemies_Blood_5 */
  12,   /* field[12] = Enemies_outpost */
  13,   /* field[13] = IfAttackEngineer */
  5,   /* field[5] = Mode_ */
};
static const ProtobufCIntRange device_to_host__frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor device_to_host__frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "device_to_host.Frame",
  "Frame",
  "DeviceToHost__Frame",
  "device_to_host",
  sizeof(DeviceToHost__Frame),
  14,
  device_to_host__frame__field_descriptors,
  device_to_host__frame__field_indices_by_name,
  1,  device_to_host__frame__number_ranges,
  (ProtobufCMessageInit) device_to_host__frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
