/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Send.proto */

#ifndef PROTOBUF_C_Send_2eproto__INCLUDED
#define PROTOBUF_C_Send_2eproto__INCLUDED

#include <protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _HostToDevice__Frame HostToDevice__Frame;


/* --- enums --- */


/* --- messages --- */

struct  _HostToDevice__Frame
{
  ProtobufCMessage base;
  float target_pitch_;
  float target_yaw_;
  int32_t x_;
  int32_t y_;
  float yaw_speed;
  float pitch_speed;
};
#define HOST_TO_DEVICE__FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&host_to_device__frame__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


/* HostToDevice__Frame methods */
void   host_to_device__frame__init
                     (HostToDevice__Frame         *message);
size_t host_to_device__frame__get_packed_size
                     (const HostToDevice__Frame   *message);
size_t host_to_device__frame__pack
                     (const HostToDevice__Frame   *message,
                      uint8_t             *out);
size_t host_to_device__frame__pack_to_buffer
                     (const HostToDevice__Frame   *message,
                      ProtobufCBuffer     *buffer);
HostToDevice__Frame *
       host_to_device__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   host_to_device__frame__free_unpacked
                     (HostToDevice__Frame *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*HostToDevice__Frame_Closure)
                 (const HostToDevice__Frame *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor host_to_device__frame__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Send_2eproto__INCLUDED */
