/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Send.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Send.pb-c.h"
void   host_to_device__frame__init
                     (HostToDevice__Frame         *message)
{
  static const HostToDevice__Frame init_value = HOST_TO_DEVICE__FRAME__INIT;
  *message = init_value;
}
size_t host_to_device__frame__get_packed_size
                     (const HostToDevice__Frame *message)
{
  assert(message->base.descriptor == &host_to_device__frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t host_to_device__frame__pack
                     (const HostToDevice__Frame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &host_to_device__frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t host_to_device__frame__pack_to_buffer
                     (const HostToDevice__Frame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &host_to_device__frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HostToDevice__Frame *
       host_to_device__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HostToDevice__Frame *)
     protobuf_c_message_unpack (&host_to_device__frame__descriptor,
                                allocator, len, data);
}
void   host_to_device__frame__free_unpacked
                     (HostToDevice__Frame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &host_to_device__frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor host_to_device__frame__field_descriptors[6] =
{
  {
    "Target_Pitch_",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(HostToDevice__Frame, target_pitch_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Target_Yaw_",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(HostToDevice__Frame, target_yaw_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "X_",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HostToDevice__Frame, x_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Y_",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HostToDevice__Frame, y_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw_speed",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(HostToDevice__Frame, yaw_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch_speed",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(HostToDevice__Frame, pitch_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned host_to_device__frame__field_indices_by_name[] = {
  0,   /* field[0] = Target_Pitch_ */
  1,   /* field[1] = Target_Yaw_ */
  2,   /* field[2] = X_ */
  3,   /* field[3] = Y_ */
  5,   /* field[5] = pitch_speed */
  4,   /* field[4] = yaw_speed */
};
static const ProtobufCIntRange host_to_device__frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor host_to_device__frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "host_to_device.Frame",
  "Frame",
  "HostToDevice__Frame",
  "host_to_device",
  sizeof(HostToDevice__Frame),
  6,
  host_to_device__frame__field_descriptors,
  host_to_device__frame__field_indices_by_name,
  1,  host_to_device__frame__number_ranges,
  (ProtobufCMessageInit) host_to_device__frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
