/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Attack.proto */

#ifndef PROTOBUF_C_Attack_2eproto__INCLUDED
#define PROTOBUF_C_Attack_2eproto__INCLUDED

#include <protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Attack Attack;


/* --- enums --- */

typedef enum _Attack__CommandType {
  ATTACK__COMMAND_TYPE__WAIT = 0,
  ATTACK__COMMAND_TYPE__FIRE = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ATTACK__COMMAND_TYPE)
} Attack__CommandType;

/* --- messages --- */

struct  _Attack
{
  ProtobufCMessage base;
  int32_t yaw;
  int32_t pitch;
  int32_t number;
  Attack__CommandType command;
};
#define ATTACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&attack__descriptor) \
    , 0, 0, 0, ATTACK__COMMAND_TYPE__WAIT }


/* Attack methods */
void   attack__init
                     (Attack         *message);
size_t attack__get_packed_size
                     (const Attack   *message);
size_t attack__pack
                     (const Attack   *message,
                      uint8_t             *out);
size_t attack__pack_to_buffer
                     (const Attack   *message,
                      ProtobufCBuffer     *buffer);
Attack *
       attack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   attack__free_unpacked
                     (Attack *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Attack_Closure)
                 (const Attack *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor attack__descriptor;
extern const ProtobufCEnumDescriptor    attack__command_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Attack_2eproto__INCLUDED */
