/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TurretCommand.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TurretCommand.pb-c.h"
void   turret_command__init
                     (TurretCommand         *message)
{
  static const TurretCommand init_value = TURRET_COMMAND__INIT;
  *message = init_value;
}
size_t turret_command__get_packed_size
                     (const TurretCommand *message)
{
  assert(message->base.descriptor == &turret_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t turret_command__pack
                     (const TurretCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &turret_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t turret_command__pack_to_buffer
                     (const TurretCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &turret_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TurretCommand *
       turret_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TurretCommand *)
     protobuf_c_message_unpack (&turret_command__descriptor,
                                allocator, len, data);
}
void   turret_command__free_unpacked
                     (TurretCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &turret_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor turret_command__field_descriptors[5] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TurretCommand, command),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(TurretCommand, yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(TurretCommand, pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TurretCommand, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "motion_status",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TurretCommand, motion_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned turret_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
  3,   /* field[3] = distance */
  4,   /* field[4] = motion_status */
  2,   /* field[2] = pitch */
  1,   /* field[1] = yaw */
};
static const ProtobufCIntRange turret_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor turret_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TurretCommand",
  "TurretCommand",
  "TurretCommand",
  "",
  sizeof(TurretCommand),
  5,
  turret_command__field_descriptors,
  turret_command__field_indices_by_name,
  1,  turret_command__number_ranges,
  (ProtobufCMessageInit) turret_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
