/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 27-Mar-2024 03:41:41
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    double d;
    double d1;
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : double L0
 *                double K[12]
 * Return Type  : void
 */
void lqr_k(double L0, double K[12])
{
  double t2;
  double t3;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2024-03-27 03:41:06 */
  t2 = L0 * L0;
  t3 = rt_powd_snf(L0, 3.0);
  K[0] = ((L0 * -166.700655487403 + t2 * 310.40496987752272) -
          t3 * 266.253098888401) -
         5.1659900740138527;
  K[1] = ((L0 * 81.818861351604454 - t2 * 325.58297699603628) +
          t3 * 363.94896624414048) +
         12.20307867941224;
  K[2] = ((L0 * -14.267427353745539 + t2 * 3.7241741648246061) -
          t3 * 4.9128674498726879) -
         0.66270337619891273;
  K[3] = ((L0 * 4.2691484838940381 - t2 * 18.271848489835989) +
          t3 * 20.07906017097195) +
         2.0771651138383529;
  K[4] = ((L0 * -33.197238930809377 + t2 * 82.500934886222979) -
          t3 * 74.510133215860961) -
         3.6260383545289989;
  K[5] = ((L0 * -15.421484000669819 - t2 * 25.135627915412819) +
          t3 * 59.735923567667669) +
         10.17334896132809;
  K[6] = ((L0 * -19.271005148269111 + t2 * 38.05563556377173) -
          t3 * 31.687940514421989) -
         4.4878263601997563;
  K[7] = ((L0 * -21.50885842237216 + t2 * 9.7047654367477048) +
          t3 * 15.767316148188669) +
         9.2267510015333478;
  K[8] = ((L0 * -85.192936703491156 + t2 * 148.2423222620086) -
          t3 * 104.9760724587584) +
         25.12413278369683;
  K[9] = ((L0 * 145.012692339202 - t2 * 356.10775862585882) +
          t3 * 319.91533093350989) +
         14.928284932628261;
  K[10] = ((L0 * -17.349495174302621 + t2 * 32.807077769741987) -
           t3 * 25.516326693488381) +
          5.2967107669759166;
  K[11] = ((L0 * 28.833930841075919 - t2 * 68.035599136499442) +
           t3 * 59.619025767661952) +
          1.517413529554708;
}

/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
