function P = all_power_cal(T,k1,k2,k3,w)
%ALL_POWER_CAL
%    P = ALL_POWER_CAL(T,K1,K2,K3,W)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2023-12-31 01:37:29

P = k3+T.*w.*(2.0e+1./1.91e+2)+T.^2.*k1+k2.*w.^2;
end
