function Vmax = Vmax_cal(Kv,Pmax,bT_gain,k1,k2,k3,w)
%Vmax_cal
%    Vmax = Vmax_cal(Kv,Pmax,bT_gain,K1,K2,K3,W)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2023-12-31 01:37:29

t2 = w.^2;
t3 = 1.0./Kv;
t4 = 1.0./k1;
t5 = w.*4.0e+1;
t6 = Pmax.*k1.*1.6e+1;
t7 = k1.*k3.*1.6e+1;
t9 = bT_gain.*k1.*7.64e+2;
t8 = -t7;
t10 = k1.*k2.*t2.*1.6e+1;
t12 = t2.*4.385844686275047e-2;
t11 = -t10;
t13 = t6+t8+t11+t12;
t14 = sqrt(t13);
t15 = t14.*1.91e+2;
Vmax = [t3.*t4.*(t5+t9-t15).*(-6.544502617801047e-4);t3.*t4.*(t5+t9+t15).*(-6.544502617801047e-4)];
end
