/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Signal.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Signal.pb-c.h"
void   signal__init
                     (Signal         *message)
{
  static const Signal init_value = SIGNAL__INIT;
  *message = init_value;
}
size_t signal__get_packed_size
                     (const Signal *message)
{
  assert(message->base.descriptor == &signal__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t signal__pack
                     (const Signal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &signal__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t signal__pack_to_buffer
                     (const Signal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &signal__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Signal *
       signal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Signal *)
     protobuf_c_message_unpack (&signal__descriptor,
                                allocator, len, data);
}
void   signal__free_unpacked
                     (Signal *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &signal__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor signal__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Signal, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned signal__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange signal__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor signal__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Signal",
  "Signal",
  "Signal",
  "",
  sizeof(Signal),
  1,
  signal__field_descriptors,
  signal__field_indices_by_name,
  1,  signal__number_ranges,
  (ProtobufCMessageInit) signal__init,
  NULL,NULL,NULL    /* reserved[123] */
};
